# Generated by Django 3.2.9 on 2021-11-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('book_name', models.CharField(max_length=255)),
                ('buy_price', models.IntegerField()),
                ('rent_price', models.IntegerField()),
            ],
        ),
    ]
