# Generated by Django 3.2.9 on 2021-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_digital',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
